module.exports = {
  share: 'a01b',
  rss: 'a068',
  qq: 'af01',
  wechat: 'af02',
  weibo: 'af03',
  zhihu: 'af0c',
  dingding: 'af16',
  dribbble: 'af0e',
  dropbox: 'af00',
  douban: 'af09',
  netease: 'af0d',
  xiaomi: 'af07',
  github: 'af04',
  gitPullRequest: 'af11',
  gitIssue: 'af12',
  gitCommit: 'af13',
  gitFork: 'af14',
  evernote: 'af05',
  facebook: 'af08',
  twitter: 'af06',
  google: 'af0a',
  wps: 'af0b',
  linkedin: 'af0f',
  processon: 'af15',
  zendesk: 'af10',
  jinshuju: 'af1A'
}
